// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Usuario actual",
  description: "Devuelve el usuario autenticado del ERP Sanamex.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail(),
      client_id: ctx.getClientId()
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.80.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool2({
  name: "search_products",
  title: "Buscar productos",
  description: "Busca productos por SKU o nombre (coincidencia parcial). Devuelve hasta 25 resultados con precio y costo.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Texto a buscar en SKU o nombre del producto")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("productos").select("id, sku, nombre, precio_venta, costo_promedio, stock_minimo").or(`sku.ilike.%${query}%,nombre.ilike.%${query}%`).limit(25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { productos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-inventory.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_inventory_default = defineTool3({
  name: "get_inventory",
  title: "Consultar inventario",
  description: "Consulta el stock actual por sucursal para un SKU. Devuelve stock por lote con fecha de caducidad.",
  inputSchema: {
    sku: z2.string().trim().min(1).describe("SKU del producto a consultar"),
    sucursal_codigo: z2.string().trim().optional().describe("C\xF3digo de sucursal opcional (ej. sv, f36). Si se omite, retorna todas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sku, sucursal_codigo }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data: prod, error: pErr } = await supabase.from("productos").select("id, sku, nombre").eq("sku", sku).maybeSingle();
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (!prod) return { content: [{ type: "text", text: `SKU no encontrado: ${sku}` }], isError: true };
    let q = supabase.from("lotes").select("cantidad, fecha_caducidad, numero_lote, sucursales!inner(codigo, nombre)").eq("producto_id", prod.id).gt("cantidad", 0);
    if (sucursal_codigo) q = q.eq("sucursales.codigo", sucursal_codigo);
    const { data, error } = await q.limit(200);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify({ producto: prod, lotes: data }, null, 2) }],
      structuredContent: { producto: prod, lotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-expiring-lots.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_expiring_lots_default = defineTool4({
  name: "list_expiring_lots",
  title: "Lotes pr\xF3ximos a caducar",
  description: "Lista lotes con stock que caducan dentro de los pr\xF3ximos N d\xEDas (por defecto 60).",
  inputSchema: {
    dias: z3.number().int().min(1).max(365).optional().describe("Horizonte en d\xEDas (1-365, default 60)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ dias }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const horizon = new Date(Date.now() + (dias ?? 60) * 864e5).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("lotes").select("cantidad, fecha_caducidad, numero_lote, productos(sku, nombre), sucursales(codigo, nombre)").gt("cantidad", 0).lte("fecha_caducidad", horizon).order("fecha_caducidad", { ascending: true }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lotes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-recent-sales.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_recent_sales_default = defineTool5({
  name: "list_recent_sales",
  title: "Ventas recientes",
  description: "Lista las ventas m\xE1s recientes (\xFAltimas 50) con folio, sucursal, total y estado.",
  inputSchema: {
    sucursal_codigo: z4.string().trim().optional().describe("Filtrar por c\xF3digo de sucursal (opcional)"),
    dias: z4.number().int().min(1).max(90).optional().describe("Ventana en d\xEDas (default 7)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sucursal_codigo, dias }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const since = new Date(Date.now() - (dias ?? 7) * 864e5).toISOString();
    let q = supabase.from("ventas").select("id, folio, fecha, total, estado, sucursales!inner(codigo, nombre)").gte("fecha", since).order("fecha", { ascending: false }).limit(50);
    if (sucursal_codigo) q = q.eq("sucursales.codigo", sucursal_codigo);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { ventas: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-pending-purchase-orders.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_pending_purchase_orders_default = defineTool6({
  name: "list_pending_purchase_orders",
  title: "\xD3rdenes de compra pendientes",
  description: "Lista las \xF3rdenes de compra con estado 'pendiente_aprobacion'.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("ordenes_compra").select("id, folio, fecha, total, estado, proveedores(nombre)").eq("estado", "pendiente_aprobacion").order("fecha", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { ordenes: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rcvqgpfbkkuiljitywpd";
var mcp_default = defineMcp({
  name: "sanamex-erp-mcp",
  title: "Sanamex ERP",
  version: "0.1.0",
  instructions: "Herramientas de consulta para el ERP de Sanamex (distribuidora farmac\xE9utica). Todas las llamadas se ejecutan como el usuario autenticado y respetan RLS y permisos por m\xF3dulo. Usa search_products para buscar art\xEDculos, get_inventory para consultar stock por sucursal, list_expiring_lots para caducidades, list_recent_sales para ventas recientes y list_pending_purchase_orders para \xF3rdenes de compra pendientes de aprobaci\xF3n.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    search_products_default,
    get_inventory_default,
    list_expiring_lots_default,
    list_recent_sales_default,
    list_pending_purchase_orders_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
